### ISSUE TITLE
How to use that MainLevelsEditor

### ISSUE THREAD

**Issue by qqbang12q** [user95401/MainLevelsEditor#1]
I mean when i try use it i can't because i don't have any tutorial for that and i got some errors
![obraz_2024-02-10_122617721](https://github.com/user95401/MainLevelsEditor/assets/159622383/eb03bb5e-5bc5-4e4c-be4e-5ff7f24556db)

**Comment by user95401** [comment]
u changed mod and want compile that?

to compile u must change cmake lists(paths) and install curly-eureka sdk

**Comment by qqbang12q** [comment]
can you make some tutorial on youtube because i still trying without effect

**Comment by user95401** [comment]
h i
soo can u explain what exactly u want?
