### ISSUE TITLE
If I haven't insert key on keyboard?? Please, rebind key on another

### ISSUE THREAD

**Issue by ChyppitauCoder** [user95401/MainLevelsEditor#13]
I have keyboard, this keyboard haven't insert! Rebind please

**Comment by ChyppitauCoder** [comment]
![IMG20240315163938.jpg](https://github.com/user95401/MainLevelsEditor/assets/140201153/074c88b0-fa49-4561-939d-5a302e90439a)

**Comment by heavyutils** [comment]
> I have keyboard, this keyboard haven't insert! Rebind please

Use reWASD
