### ISSUE TITLE
Wtf is happening

### ISSUE THREAD

**Issue by VladPlayGH** [user95401/MainLevelsEditor#16]
All the songs got replaced with spin-off songs, why is that happening?

**Comment by user95401** [comment]
moregames mod maybe

**Comment by user95401** [comment]
oh its u again

**Comment by VladPlayGH** [comment]
> oh its u again

yes

**Comment by VladPlayGH** [comment]
> moregames mod maybe

no

**Comment by user95401** [comment]
wait..a 
u tried v6 beta?

**Comment by VladPlayGH** [comment]
> wait..a u tried v6 beta?

hold on let me try

**Comment by VladPlayGH** [comment]
that didn't do anything

**Comment by user95401** [comment]
i think its dublicate

**Comment by user95401** [comment]
drop _AudioTracks.ini content

**Comment by VladPlayGH** [comment]
i think now i understand why because:

[0]
Title = Stereo Madness
Filename = StereoMadness.mp3


[1]
Title = Back On Track


[2]
Title = Polargeist
Filename = Polargeist.mp3


[3]
Title = Dry Out


[4]
Title = Base After Base
Filename = BaseAfterBase.mp3


[5]
Title = Cant Let Go


[6]
Title = Jumper


[7]
Title = Time Machine


[8]
Title = Cycles


[9]
Title = xStep


[10]
Title = Clutterfunk
Filename = Clutterfunk.mp3


[11]
Title = Theory of Everything
Filename = TheoryOfEverything.mp3


[12]
Title = Electroman Adventures


[13]
Title = Clubstep
Filename = Clubstep.mp3


[14]
Title = Electrodynamix


[15]
Title = Hexagon Force


[16]
Title = Blast Processing


[17]
Title = Theory of Everything 2


[18]
Title = Geometrical Dominator


[19]
Title = Deadlocked


[20]
Title = Fingerdash


[21]
Title = Dash
Filename = Dash.mp3


[60]
Title = Whats a Future Funk
Filename = geode\config\user95401.mainlevelseditor\audio\Whats a Future Funk (701013).mp3


[58]
Filename = geode\config\user95401.mainlevelseditor\audio\Wet Willy (10007267).mp3
Title = Wet Willy


[57]
Filename = BackOnTrack.mp3
Title = Unknown


[56]
Filename = BackOnTrack.mp3
Title = Unknown


[45]
Filename = BackOnTrack.mp3
Title = Unknown


[43]
Title = Unknown


[26]
Filename = DJRubRub.mp3
Title = Secret


[61]
Title = Menu Theme
Filename = geode\config\user95401.mainlevelseditor\audio\Menu Theme (584131).mp3


[-1]
Title = Practice: Stay Inside Me


[41]
Filename = BackOnTrack.mp3
Title = Unknown


[55]
Filename = BackOnTrack.mp3
Title = Unknown


[36]
Filename = MonsterDanceOff.mp3
Title = Monster Dance Off


[23]
Filename = The7Seas.mp3
Title = The Seven Seas


[53]
Filename = BackOnTrack.mp3
Title = Unknown


[29]
Filename = Machina.mp3
Title = Machina


[59]
Title = Unknown


[54]
Title = Unknown


[52]
Title = Unknown


[51]
Title = Unknown


[50]
Title = Unknown


[49]
Title = Unknown


[48]
Title = Unknown


[47]
Title = Unknown


[46]
Title = Unknown


[44]
Title = Unknown


[42]
Title = Unknown


[40]
Title = Unknown


[39]
Title = Power Trip


[38]
Title = Nock Em


[37]
Title = Press Start


[35]
Title = Round 1


[34]
Title = Embers


[33]
Title = Striker


[32]
Title = Space Pirates


[31]
Title = Frontlines


[30]
Title = Years


[28]
Title = Beast Mode


[27]
Title = Payload


[25]
Title = Airborne Robots


[24]
Title = Viking Arena


[22]
Title = Explorers

**Comment by VladPlayGH** [comment]
why i can't add levels with the beta anymore?
why is it an empty menu?

**Comment by user95401** [comment]
because its unfinished

**Comment by VladPlayGH** [comment]
> because its unfinished

how can i add levels then

**Comment by user95401** [comment]
manually if v6beta

**Comment by user95401** [comment]
just dont use v6

**Comment by VladPlayGH** [comment]
add that you can change the difficulty, name and stars amount please

**Comment by user95401** [comment]
maybe i can controll difficulty sprite node

**Comment by VladPlayGH** [comment]
ok
