### ISSUE TITLE
turns every demon level into a hard demon💀

### ISSUE THREAD

**Issue by pkojopeer** [user95401/MainLevelsEditor#17]
self explanatory (v5.00 and v6.00 beta does this) 
![image_2024-03-24_184148413](https://github.com/user95401/MainLevelsEditor/assets/155401556/a058f307-5bab-49c7-b0e9-7559075550a6)

**Comment by user95401** [comment]
turn off that shit 
![image](https://github.com/user95401/MainLevelsEditor/assets/90561697/eb2ff2d9-ae76-48c4-bb95-c836b933581a)

**Comment by pkojopeer** [comment]
fix it now😈😈😈😈😈😈😈😈😈😈😈

**Comment by heavyutils** [comment]
Skill issue, doesn't happen for me

**Comment by heavyutils** [comment]
WAIT WHAT DID YOU BEAT SLAUGHTERHOUSE? WOW
