### ISSUE TITLE
IMPORTANT BUG! NEEDS TO BE FIXED

### ISSUE THREAD

**Issue by Stupidgmes** [user95401/MainLevelsEditor#22]
okay I lied just make it for mobile  🥺 pwwweese?

**Comment by user95401** [comment]
last beta can be loaded on mobile to see how many work is here for me

**Comment by user95401** [comment]
![Screenshot_20240401_080945_com geode launcher](https://github.com/user95401/MainLevelsEditor/assets/90561697/d268363a-4c2b-4562-89b5-cdfc3a14e76b)
![Screenshot_20240401_081020_com geode launcher](https://github.com/user95401/MainLevelsEditor/assets/90561697/7bd27f84-51cb-484d-ac82-561bd9b2cee5)
![Screenshot_20240401_081144_com geode launcher](https://github.com/user95401/MainLevelsEditor/assets/90561697/5276685a-cf7d-4e0e-9eaa-1ab17ace05d5)

**Comment by Catavory7** [comment]
> ![Screenshot_20240401_080945_com geode launcher](https://private-user-images.githubusercontent.com/90561697/318335101-d268363a-4c2b-4562-89b5-cdfc3a14e76b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MTk1NDcsIm5iZiI6MTcxMjcxOTI0NywicGF0aCI6Ii85MDU2MTY5Ny8zMTgzMzUxMDEtZDI2ODM2M2EtNGMyYi00NTYyLTg5YjUtY2RmYzNhMTRlNzZiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDAzMjA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2YmMyY2RjYWVhMjhiNWFhZWNmN2ZmMWZkMmMyYjU1M2ViNDMxYjhiYTNkYmM0YjNmN2YwMzY4NzRlNzI5ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UoREHZ75W9acumisrJbYvALZWmer6LpgOCYlGruTjjo) ![Screenshot_20240401_081020_com geode launcher](https://private-user-images.githubusercontent.com/90561697/318335109-7bd27f84-51cb-484d-ac82-561bd9b2cee5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MTk1NDcsIm5iZiI6MTcxMjcxOTI0NywicGF0aCI6Ii85MDU2MTY5Ny8zMTgzMzUxMDktN2JkMjdmODQtNTFjYi00ODRkLWFjODItNTYxYmQ5YjJjZWU1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDAzMjA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjNmYzZGRkNWQ0ZDFhYTQxMTIxYWI4ZDQ4M2Y0YzQyZDNiN2VmODEzY2E4MmI0YWU1Y2E1YjZhYzhjNjczZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.41ssURk42os9Q1RQhbywaOl0CSVp71BV1wVfX-Bt43w) ![Screenshot_20240401_081144_com geode launcher](https://private-user-images.githubusercontent.com/90561697/318335120-5276685a-cf7d-4e0e-9eaa-1ab17ace05d5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MTk1NDcsIm5iZiI6MTcxMjcxOTI0NywicGF0aCI6Ii85MDU2MTY5Ny8zMTgzMzUxMjAtNTI3NjY4NWEtY2Y3ZC00ZTBlLTllYWEtMWFiMTdhY2UwNWQ1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDAzMjA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0MzNiN2ZjOWY0MjlhZGZkOWU0ZjQ0N2Q5NTZhZDk5ZDA0MDQzODAzOTE0MDVhZmViNzRjMGU5NjNkYjY5MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.97fX1zetZW0s8mY9-wE9GcSlFaI-9xSMufpx7gham48)

Where do I download

**Comment by user95401** [comment]
latest release

**Comment by Catavory7** [comment]
> latest release

Can you send me the latest release

**Comment by user95401** [comment]
https://github.com/user95401/MainLevelsEditor/releases/latest
