### ISSUE TITLE
Custom main songs

### ISSUE THREAD

**Issue by ExtremeSpe** [user95401/MainLevelsEditor#24]
I've tried adding a new main song, I added the song file to resources folder, added it to audiotracks.ini and I tried updating one levels song to my new main song, but it didn't work. I just don't know if it's impossible or I just messed something up

**Comment by user95401** [comment]
send ur config files
i will see and so say what may be wrong

**Comment by ExtremeSpe** [comment]
[my configs.zip](https://github.com/user95401/MainLevelsEditor/files/15030438/my.configs.zip)
had to post it as zip

**Comment by user95401** [comment]
old version seems. 
in v6.0.0-beta.6 (i think v5 also)
structure is
```ini
[AUDIO_TRACK_ID]
Title = AUDIO_TRACK_NAME
Filename = FILE_PATH
```

**Comment by user95401** [comment]
![Screenshot_20240419_082520_com alphainventor filemanager](https://github.com/user95401/MainLevelsEditor/assets/90561697/bc317155-2759-4328-bb7f-0dfe661c9000)

**Comment by ExtremeSpe** [comment]
it worked, I just installed old version before and used it's path lol, but anyways how do I change the song artist? djvi definitely didn't make the music that I added

**Comment by heavyutils** [comment]
DJVI also did not make Secret (afaik)

**Comment by heavyutils** [comment]
And where do you see the artist on a Main level? Lmao

**Comment by heavyutils** [comment]
If it's for custom levels, use the Jukebox mod
