### ISSUE TITLE
load failed bypass?????????

### ISSUE THREAD

**Issue by error-404-usernotfound** [user95401/MainLevelsEditor#25]
It says "load failed bypass here" but there's no hyperlinks around it or anything? how do I activate this bypass I need it!

(ps: either fix compatibility with the main level pages mod or if that's impossible add a button to copy any main level to your saved level list pls)

**Comment by user95401** [comment]
its by default already hooked
i mean here is always load failed bypass

**Comment by user95401** [comment]
main level pages mod seems to be working in v6 beta 7

![Screenshot_20240422_082610_com.geode.launcher.jpg](https://github.com/user95401/MainLevelsEditor/assets/90561697/4ad36c8e-0707-40f4-beda-9e03b8673b3b)
