### ISSUE TITLE
android support would be so flipping cool

### ISSUE THREAD

**Issue by polygoners1** [user95401/MainLevelsEditor#30]
android support would be so awesome!
it would be so cool!
ok im not putting the entire lyrics in here btw but just imagine being able to put in custom main levels into the menu on android!
i would love that.

**Comment by user95401** [comment]
install v6 last beta

**Comment by polygoners1** [comment]
> install v6 last beta

where?

**Comment by polygoners1** [comment]
> > install v6 last beta
> 
> where?

oh wait i found it and i am now downloading it on my phone. thx!
