### ISSUE TITLE
Renamed all of my levels to my latest level's name

### ISSUE THREAD

**Issue by RL3D** [user95401/MainLevelsEditor#36]
![20240515170632_1](https://github.com/user95401/MainLevelsEditor/assets/93167795/cf5ffa96-1607-4ede-9f46-a217f89242e0)

Context:
When I was trying to play "How to Clutterfunk" it keeps refreshing the page instead of taking me to the level. So I used GDShare to copy the level. But then I noticed that most of my levels were suddenly renamed to the level I have on top, in this case "Dash Full".

When I try to rename the level, it will just keep it to "Dash Full".
When I create a new level, it renames itself to "Dash Full" when I exit the level's info page.

I was trying all solutions to this problem, spent all day trying to figure out this bug. I temporarily removed Geode from my game and suddenly, the bug is fixed. I did some investigation on the mods, and sure enough, your mod is causing this problem.

**Comment by boibest** [comment]
yeah im having the same issue
