### ISSUE TITLE
About Local custom Levels for main levels.

### ISSUE THREAD

**Issue by Arrhythmiagamer23** [user95401/MainLevelsEditor#4]
Is there a way to add custom levels into main levels with a tool that you can make?

**Comment by user95401** [comment]
i ii i whaa

**Comment by user95401** [comment]
level string converter or whaat

**Comment by Arrhythmiagamer23** [comment]
well i tried to get the custom levels into main levels in 2.2, but it didn't work! can you make one for 2.2?

**Comment by user95401** [comment]
u want put some level but then u replace string in txt file u getting Load Failed! error?

**Comment by Arrhythmiagamer23** [comment]
oh, right!

**Comment by Arrhythmiagamer23** [comment]
can you make a 2.2 level manager?

**Comment by user95401** [comment]
i planned some tools in game when i port it to geode

**Comment by Arrhythmiagamer23** [comment]
ok

**Comment by Arrhythmiagamer23** [comment]
did you implement it yet?

**Comment by user95401** [comment]
## doin stuff

![image](https://github.com/user95401/MainLevelsEditor/assets/90561697/9e904b16-03e2-4af9-af57-5a0edde4f5bb)
![image](https://github.com/user95401/MainLevelsEditor/assets/90561697/beb0bbb4-93e4-4dad-bad0-79ba182d17b9)
![image](https://github.com/user95401/MainLevelsEditor/assets/90561697/23f6611c-a6e2-4418-8418-1c5cbb4da4ec)

**Comment by Arrhythmiagamer23** [comment]
good

**Comment by Arrhythmiagamer23** [comment]
can you try releasing the version you're making as a beta?

**Comment by user95401** [comment]
umm no 
im going to finish it in some hours

**Comment by user95401** [comment]
[user95401.mainlevelseditor.zip](https://github.com/user95401/MainLevelsEditor/files/14474526/user95401.mainlevelseditor.zip)
oke play around

`change .zip into .geode

**Comment by Arrhythmiagamer23** [comment]
ok

**Comment by Arrhythmiagamer23** [comment]
how can i add a local level as a main level?

**Comment by user95401** [comment]
### helpers:
hold `Insert` to automatically setup online or local level into main levels
hold `Delete` to automatically delete main level (in level select layer)

**Comment by Arrhythmiagamer23** [comment]
ok

**Comment by user95401** [comment]
:D 
https://github.com/user95401/MainLevelsEditor/releases/tag/v4

**Comment by user95401** [comment]
feature added in v4 :D
