### ISSUE TITLE
I imported the level, and the difficulty, stars, name, and orbs are all there, but when i play the level, its stereo madness lol

### ISSUE THREAD

**Issue by Foxiseminger** [user95401/MainLevelsEditor#42]
do i remove the H4sIAAAAAAAAC off my level data?

**Comment by user95401** [comment]
no

**Comment by user95401** [comment]
where is a level string?

**Comment by Foxiseminger** [comment]
in C:\Users\Fox Iseminger\OneDrive\Desktop\.exe's and game dir\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\geode\config\user95401.mainlevelseditor\levels

**Comment by user95401** [comment]
file content is actually ur level?
