### ISSUE TITLE
Does the mod allow to use custom levels' songs in editor?

### ISSUE THREAD

**Issue by masckmaster2007** [user95401/MainLevelsEditor#43]
I'm trying to see how to do it and I can't find it. It does seem to bypass if I edit the custom levels. However, I can't do it on user/created levels...

Did I do anything wrong?

**Comment by user95401** [comment]
use songs that was copied via this thing?
![image](https://github.com/user-attachments/assets/aad46437-f5c9-4764-8bb9-ac3679547b73)

orrr whataa 
i dont understand

**Comment by user95401** [comment]
and use in editor like here?
![image](https://github.com/user-attachments/assets/24d43b4e-6161-49d8-a426-99bddb15c955)

**Comment by masckmaster2007** [comment]
oooh. Will try. I force imported them by copying json files...

**Comment by masckmaster2007** [comment]
![image](https://github.com/user-attachments/assets/b332b8aa-3939-4400-8905-ee937d663425)

btw, it is shown like this

**Comment by user95401** [comment]
robtop limit here

**Comment by masckmaster2007** [comment]
a

**Comment by user95401** [comment]
i change audio selector later
