### ISSUE TITLE
Weird level bug

### ISSUE THREAD

**Issue by CountryLand69** [user95401/MainLevelsEditor#44]
So after I downloaded the mod, for some reason all the levels just go back to 0%, they still have all 3 coins and that stuff, the levels are already completed still and I know that because I tried beating one of the levels again but it stayed 0%, is this a visual bug or something?

**Comment by user95401** [comment]
oh fuck i just now paid attention to this
i think its really 0% for every level due tooo aa idk lol

even new best shows
![image](https://github.com/user-attachments/assets/61eea869-3b22-44ce-a878-de5a465e91a0)

**Comment by user95401** [comment]
### fixed in [v7.0.0-beta.11](https://github.com/user95401/MainLevelsEditor/releases/tag/v7.0.0-beta.11)
