### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by ForgottenTake** [user95401/MainLevelsEditor#46]
I have no Idea how to use this and can't find any documentations for this so I don't know what I am supposed to do or how this mod even works. All I know is that i can change the details of the main levels, and I don't know anything else and Its driving me crazy because I cant find out how to use it, or if its even working.

**Comment by user95401** [comment]
enable this and do what u want 
![image](https://github.com/user-attachments/assets/7129934d-0aa9-42bc-9acd-7ecba04715b6)

**Comment by ForgottenTake** [comment]
I cant find the setting for the mod.

**Comment by user95401** [comment]
![image](https://github.com/user-attachments/assets/4dd03e4f-5afb-491b-9e10-c5bd3d773e52)
![image](https://github.com/user-attachments/assets/2829e3af-3dd9-4a95-a7d5-c237f2c0b213)
![image](https://github.com/user-attachments/assets/679c88ff-1a80-4e9a-8ecb-1bc67605d387)

**Comment by ForgottenTake** [comment]
thank you

**Comment by ForgottenTake** [comment]
is there a way to reset all of the levels?

**Comment by user95401** [comment]
delete mod config
