### ISSUE TITLE
I can't set my local levels as main levels!

### ISSUE THREAD

**Issue by Arrhythmiagamer23** [user95401/MainLevelsEditor#5]
i tried to press Ctrl+G on my level i created but, it dosen't let me! can you implement it?

**Comment by user95401** [comment]
popup dont opens?

**Comment by Arrhythmiagamer23** [comment]
right! for my local levels! can you implement it?

**Comment by user95401** [comment]
u can just upload it huh

ok i add it for local level page layer

**Comment by Arrhythmiagamer23** [comment]
ok!

**Comment by user95401** [comment]
feature added in v4 :D
