### ISSUE TITLE
🥺please update to 2.2074

### ISSUE THREAD

**Issue by DevonMKatYT** [user95401/MainLevelsEditor#54]
once again thank you for adding my suggestions so far, i feel like i'm really a great supporter to this amazing mod, but god please update it🥺🥺🥺🥺 thanks

**Comment by user95401** [comment]
v7.0.**2**-beta.15 update for 2.2074 was released last week.
https://github.com/user95401/MainLevelsEditor/releases/tag/v7.0.2-beta.15

Make admins unban me, if u want see mod on geode servers. I already updated all my mods on time of first releases of geode sdk v4, but can't publish updates.

**Comment by DevonMKatYT** [comment]
good to know. thank you, is there any way I can still use the mod in-game?

**Comment by user95401** [comment]
manual installing the .geode file from release
![image](https://github.com/user-attachments/assets/6d316641-fd1d-42df-9c2e-345c1df05da8)

**Comment by DevonMKatYT** [comment]
thanks, I am once again making stuff with this masterpiece!!!
