### ISSUE TITLE
Feature! 

### ISSUE THREAD

**Issue by relaxingOcean** [user95401/MainLevelsEditor#6]
Please add a default setting that can be turned off that prevents stat gains... accidentally got 2,700+ stars and 69,000+ orbs
also bring over the stats from already completed levels so it doesn't look like it's a completely different level

**Comment by user95401** [comment]
stat gains prevent will be added
but not sure about bring over stats huh

**Comment by KiloBreeze** [comment]
It happened with me too, I got 40,000 stars and god who knows how many orbs

**Comment by user95401** [comment]
![image](https://github.com/user95401/MainLevelsEditor/assets/90561697/f8dd0d47-285f-4fdd-b87d-5062cf5def79)
stat gains prevent was added
