### ISSUE TITLE
Copy editor levels; another way.

### ISSUE THREAD

**Issue by heavyutils** [user95401/MainLevelsEditor#8]
Hi, it's me again. I don't use a geometry dash account normally, so I can't access the share layer. Maybe make a way to copy my editor levels another way that's possible without? It can simply default to NA 0 star. Turning the whole level into a custom object is a bit tedious. Alternatively you can make the share layer accessible without account but nonfunctional to upload to servers, exactly like it was in 2.1.

**Comment by user95401** [comment]
there is a button 

![image](https://github.com/user95401/MainLevelsEditor/assets/90561697/1788b8f0-74cc-482c-a4b7-edebee8db739)
![image](https://github.com/user95401/MainLevelsEditor/assets/90561697/f73be18a-aecd-426c-a3c3-8e0564fdbf5c)
